### PR TITLE
Partial typing and fix test

### PR DESCRIPTION
**Pull request by 0xA-10**
Fix `partial`'s output type to actually be a partial (except use a custom type which also allows keys to be null).

There were a couple tests using error strings as their validation but were failing because the output now seems to omit the error name. Not sure if it's mocha or typescript or what that changed this but I've strings to match (they're still throwing the correct errors).

### CODE REVIEW

**Comment by wms** [comment]
It's likely a Node version change that's causing the name of the error to change; probably worth confirming and making the actual fix version-dependent or otherwise able to differentite  between different forms of error name.

I'd probably favour at least type alises that make better use of composition over the 'partial' and 'nullable' traits.

**Comment by 0xA-10** [comment]
> It's likely a Node version change that's causing the name of the error to change; probably worth confirming and making the actual fix version-dependent or otherwise able to differentite between different forms of error name.
> 
> I'd probably favour at least type alises that make better use of composition over the 'partial' and 'nullable' traits.

That's a good point, I'll see what I can do to make the tests version agnostic.

Would you be able to elaborate on the second point? Is doing this what you mean:
```
export type Nullable<Val> = Val | null | undefined;

export type Partial<Val> = {
  [Key in keyof Val]?: Nullable<Val[Key]>;
}
```

Thanks for the feedback.

**Comment by 0xA-10** [comment]
Removed the test edits from this PR

**Comment by wms** [comment]
I was thinking something along the lines of:

```typescript
export type NullableObj<Val> = {
  [Key in keyof Val]: Val | null | undefined;
}

export type NullablePartial<T> = Partial<NullableObj<T>> // uses TS builtin type `Partial<T>`
```

**Comment by 0xA-10** [comment]
> I was thinking something along the lines of:
> 
> ```ts
> export type NullableObj<Val> = {
>   [Key in keyof Val]: Val | null | undefined;
> }
> 
> export type NullablePartial<T> = Partial<NullableObj<T>> // uses TS builtin type `Partial<T>`
> ```

Ah that makes more sense. Added in e3fe5ca.

**Review by wms — APPROVED** [review]

**Review by nateabele — APPROVED** [review]
Looks good. Somebody wanna bump the version and deploy?

**Comment by wms** [comment]
@anatelli10 Can you raise another PR that increments the minor version number?

**Comment by 0xA-10** [comment]
> @anatelli10 Can you raise another PR that increments the minor version number?

https://github.com/ai-labs-team/ts-utils/pull/19

**Pull request merged**
